import 'package:fluentui_system_icons/fluentui_system_icons.dart';
import 'package:flutter/material.dart';

const IconData emailIcon = Icons.email;
const IconData userIcon = Icons.person;
const IconData passwordIcon = Icons.password;
const IconData arrowBack = FluentIcons.arrow_left_12_regular;
const IconData backspaceIcon = FluentIcons.backspace_16_regular;
const IconData dropDownIcon = Icons.arrow_drop_down;
const IconData searchIcon = FluentIcons.search_16_regular;
const IconData personalChatIcon = FluentIcons.person_chat_16_regular;
const IconData groupChatIcon = FluentIcons.chat_multiple_16_regular;
const IconData starIcon = FluentIcons.star_16_filled;
const IconData starHalfIcon = FluentIcons.star_half_16_regular;
const IconData clockIcon = FluentIcons.clock_16_regular;
const IconData callIcon = FluentIcons.call_16_filled;
const IconData callRegularIcon = FluentIcons.call_16_regular;
const IconData videoIcon = FluentIcons.video_16_filled;
const IconData arrowCircleUpLeftIcon =
    FluentIcons.arrow_circle_up_left_20_filled;
const IconData chatIcon = FluentIcons.chat_16_regular;
const IconData addIcon = FluentIcons.add_16_regular;
const IconData checkmarkIcon = FluentIcons.checkmark_16_regular;
const IconData personIcon = FluentIcons.person_16_regular;
const IconData signOutIcon = FluentIcons.sign_out_20_regular;
const IconData lockClosedIcon = FluentIcons.lock_closed_16_regular;
const IconData alertIcon = FluentIcons.alert_16_regular;
const IconData emojiIcon = FluentIcons.emoji_20_filled;
const IconData micIcon = FluentIcons.mic_16_regular;
const IconData attachIcon = FluentIcons.attach_16_regular;
const IconData cameraIcon = FluentIcons.camera_16_filled;
const IconData doubleArrowIcon = Icons.double_arrow_rounded;
const IconData sendIcon = FluentIcons.send_16_regular;
const IconData documnetIcon = FluentIcons.document_20_filled;
const IconData imageIcon = FluentIcons.image_20_filled;
const IconData headphonesIcon = FluentIcons.headphones_20_filled;
